version: '3.9'

services:
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jupyter
        command: >
            bash -c "sudo jupyter notebook --ip=* --port=8888 --NotebookApp.token='admin' --allow-root"
        ports:
            - 8000:8888
        restart: always
        volumes:
            - ./data:/app